# netlify.toml （リポジトリ直下）

[build]
  command = "npm ci && npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # ESMファイル（src/**, data/**）をLambdaに確実に同梱する
  included_files = ["src/**/*", "data/**/*"]

# サイト全体のセキュリティヘッダ
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# ← ここがポイント：関数パスは /.netlify/functions/*
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Session-Id"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
